remote_theme:       "StartBootstrap/startbootstrap-clean-blog-jekyll"
title:              The Basement
email:              mukherjeeabhirup44@gmail.com
description:        Personal website of Abhirup Mukherjee
author:             Abhirup Mukherjee
url:                "https://abhirup-m.github.io"

# Social Profiles
twitter_username: abhirup_mjee
github_username: abhirup-m
facebook_username: Seary.Blue
instagram_username: searyblue
linkedin_username: abhirup-mukherjee-665588229

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-4NY99EHY8J # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
