locale                   : "en-US"
title                    : "The Basement"
title_separator          : "-"
subtitle                 : "Abhirup Mukherjee"
name                     : "Abhirup Mukherjee"
description              : "Graduate student, India."
github                   : [metadata]

analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-4NY99EHY8J"
    anonymize_ip         : # true, false (default)


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  math_engine: katex
  parse_block_html: true
  highlighter: rouge

# Defaults
defaults:
  - scope:
      type: posts
    values:
      layout: posts
      katex: true
      figCounter: 1
  - scope:
      type: pages
    values:
      layout: pages
